language: ruby
bundler_args: --without kitchen_vagrant --without development
rvm:
- 1.9.3
cache:
  bundler: true
before_install:
- sudo apt-get install -qq libgecode-dev
- echo -n $DO_KEY_CHUNK_{0..30} >> ~/.ssh/id_do.base64
- cat ~/.ssh/id_do.base64 | tr -d ' ' | base64 --decode > ~/.ssh/travis.pem
- ls -la ~/.ssh
script:
- bundle exec foodcritic -f any .
- bundle exec rubocop
- bundle exec rspec -fd
- bundle exec kitchen test $KITCHEN_INSTANCE
after_script:
- bundle exec kitchen destroy
branches:
  only:
  - master
env:
  global:
  - secure: HPouOFMikLNIzoHJNcLmoQqJFsqXJHS2LUyEc+g7bC6HzjfxPveBs+hlvxPXodCfKRf0poMIHxiVCSRJkHcOB/hwAbpvmsV1J1eyIqxfeDWi02dRDM5zt0d8pQUheBJmZIEVuyWsv5aW6zl8kbhfrLrrJeq7quNQv2yrEL544SM=
  - secure: ZQQZnjIxF0SzZb+k5q1njlBrn001C7MTNQWTZTn41DiI1fiB9SFh3zAQTqYsplWBoAB1OOhUTFSFtvRmB6mpKZmKCdFStHttMt++wy0lNcReTA4XmwpPqO7mX431+u9ibOBM8KxMAo2netvAtakKVN5E2YoTIF/Clec/uHFlgc4=
  - secure: EHFaBgpNP4glGItKaPiA0ENV+hpSB873B38fDgN+Hr7msxhqMwveWUK/EJ08UyzPFLzaSDMhtT/t/0NZOlzZMSrIsYdR5gafjxqKc+8ap2yPr5WA1k7Z/foA2gJ26RihIu1NMa5Bxr0qwXZw39y1Eqay1c3G5+NGbR04u+7XxaM=
  - secure: KFZvIkkh3wCALosE5BYWHFCy9oaL4VzK4qLRcX2sqmE+31q+jTZlk2frcyM1xD0PpD/E4SGcgt3XXKrwxYNcXPYDsKdTXOddNQTOqwaM3m1dg/I322l7RjkaIBeUQwKAkSPs9TsraRaVCIOWoifkGNif6Dip8ootbfkBtO3BUX8=
  - secure: PTA5Z/IaWR8Euh/LOi9LeP2XzokorGXP/of5akK3ar0otB9xlDN3Hn0PpoAnzTeM76U1BJm6KLQDmnXegEelzaKfS6xJGnyk3GLkSW43e5OupIOYfzQexXMqg5Y+ZiGqnzUnA7jNL1LixyH3xvXs4UMFx1ivzXd6oMxrdKygu7k=
  - secure: ZXFIQSwV0tRORrjozZX29hZzBy7+My44pZM6RHqZEJ4NsZ+PCSTwpkk0dVuQXXp8rYpIRWUhaAxkvDEY5yxMvmCtmSXoJ/yXstpCBzO+1AgNtEstNtS5LYuK6pIHaAmQysA6Jif0VhPr2xWUlFVLa12x/6xP5CAsOW5rqkk2ng4=
  - secure: DIeIvI5/oVvqIaNNiO3oAanTI1aMgL/onac9JxFL+PE4eE0jCUCcKKKw8eIN70W6icJevf+Sja/iVGh3BP/8n/zQFzf+7IzKP8X23goKH5dFVEqvqmANd3JcTlVJrt4rP3mGzCJjo1uqLmwW3SejG9EKZDSsvKTBN5j2Av0tVd0=
  - secure: IFUZWzmiCLG1RSuWsceaJDUvG6K2z352HdQ9NI/S3/rdYr5gk2D4/Uf7xdhXA/23rPGCWlzC0ZYmiPlRQKrTUZLS4WHFT8KRwjRrk5LDDlSV5wwkkphzhicp/KpV6xAsKqxa9A/yqiBEHn1EBGCCQTRPWSLzw4kmM6DIXMVGTR4=
  - secure: dPPSL6Fr8UM05o/PV7emAdWJ2wrpb+Gy34DqYzcgS0m9hrbbPt8BaKZ7ptt7h5eJ+8v0XhkBElKCoyOxnCCp+kpaqmLw2YFWb72jNS0eO0HgLsEFlAGiZYcgpl+CikeCtKIrY62EjCEfY9B5eaWLYi8miJlQbBOZ5nzznMVkb3g=
  - secure: dCUc+JVpj3hqHYmvqmBLCkgZfOvSnpS9tsJKIX80dtSeAZd6vzbBdfiiZVRf0Ft2ZvYhx+IuLlDI+KZ29LX4qxBNrwDoe1E9SxGUZQe40yeBPYhU+DTepH/Zdiabtyd7R032PsxE0ZXqSdmZbY/RuRchMYGcIOVXbrpg+kvKtPw=
  - secure: SjdFTk9KSXJrCsNymdaOLAHPZKMTXWSVwe2DD4EO1vO7XqUO2EvWytTnYyZQY6HltLCNVJBjvDSnhEFQSTUBgViBkr+XHUrRa9rfPXRp1G10l/X+RcIeh4XFDjKowE1Je+Ox+/Fuwsn7MVHlukRYCFPxDue7vRvDfQf6bBxhYsU=
  - secure: gY7RgVvn1hBCEKp/Uq2kJ82w6D977EvpMrll99TOYUESQ8yGxPJ82zVWrgBz9qE12zoakWP7qa9iUzBuG4FibrxD4wjs4ZvTPbs+5FKNEUObzwXEwfOhbbW7rIxL/+8hWBHP+92PJxeJsV1/1GcfpjSE2YPIUZNNWIq8+ltpN+E=
  - secure: KL4ZFF/Vno7opAJOrAgZd/G85+uJhldrjHnwyByLpUz44JgWl2KiSSC0vFS9LeKOpo2pm4iuKoXXVgvVplaWuQMbENTphlN2xIQ9C2Pq6IB1UI4ARn+U1/NrHir3YQ6HXvPm8G7KPwptY3XjnAHbpjf0tzrTfzV8g5ULZ5l8UyI=
  - secure: FSsEn3AuMiKUWJwS+wOoEX+jBaglSOkgNzHLuwoP9cI16qpy2cqawvdLn6fskeVWUFasoM6Aoy+x16jZpZ5gv6BrnkdheGA7KmRUE39QxSqzgnRhUSBZG89POl+KyE9fMkW5ZTzxz4+KbWwIyF73RaPZT1gkojLmWPrLGkDXpTw=
  - secure: KGJPyIroqtf7izBFcJoulhzFx2EqJBQZNxiS5wx6lfh5AGEl1gp9Bx9OjMzq5KsAIT0ukC7ViiQmpBmdcLEPzYdZJTYCmu0nyTlJO+B3sjR7+lq4g8oI/a6c617WOSRylHNHcojDhAI/vl/PbNEfUjWthZ8M8L88yoOb7D4JGbU=
  - secure: JIAEwbkzE9kKl/zrBW2ORGred2TeYq6FB6dJkz3N9xjrLVW3Qd/Ymjm9ItsETLwl5PFxqzDUb+S01OJpI0NsdJX9QrC4cq/EnEK5EZhQds9pubJHtuIn0GjtYl+HkMYccBm0h7hkDJKGWHGEJCOZ/dVTh8ANOHwWAwx0TfFgf2Q=
  - secure: Wxa3eBOUMVTKMXe6iFhplWlM+eGxRIhQmrZ4z5XmwU5pMLmtwbWEaedWcJWj9lYekRB+FNZq0lgXB5Fe9ujdvye3jZRMIxRCexjCfExi2PxWztlRMgMT1z8gWAArqg8Gk9fx5wd/AxlNQHifdKDQFbTgft+/z1e/f+T/K5UCQRw=
  - secure: bRToId+eVIfBTuJ4ETTjuQkxg/M/wk47C0GA95zkhrM215JUrL4hv83kPbJbjiqykalvqVG7ko5nitiaBfIfFp5TIBo6p4B7lO9jvmAHYpdn+Iu/Av/mdnnuvO1TbAnvULWZmKPGno03rhWmMN40fzFR/iZHtn92VX1i4m+lCm4=
  - secure: WObsVTe9msY3cDLennrTCyu8J3xE6bnL4SlBoxm+ggVae3eiX7XIVnAhMYBW0SOWMHyCOkcKevp/qp6HW6Nm0Bmkp1FSgfSYyNGPa7RKRIxEvRELtmQwlfJ15Reje64Z0+sQ9pFQFTRoLwgF5BlFNSrPsgwjlR9CbDdOoipzTNM=
  - secure: Fkcpu3XYH9oTCMCvJmUHAOsEyjbcR1L0hu7a/Vj7bu8xb5gI0bMLD7HfAd8SSPbi/89ecEQhmBye6MVFR057A+LM7hC5QK52MbE9kueemIOngYLodJgEAoV0uK3Cn/0hMDWXh0egddHaVK0nAy2neioG27r4jHSBMDnsCJlCpBY=
  - secure: PjU4MN0OZePbH9fb2eVJnHzIxJF/tygnFG340/9iFDbuJRq8Uus5bSGqATECHyo8ApjWi3DpRDWOqcpMd9g1OgYjaNSlC1tp0J56bFD4wc2p/glJE5P4IZ7XlNqA/DwhgWcu8CQe8ZMlV3uerUTSj5+wEKlLA0nclsDGNfEa5NY=
  - secure: TSw1zKlsJncTeTBr3l4N2EwJL1VujDHsAklaS0UTNIX6NkrfoYKGHDAaAc5MNcG3Z/1ewmrVf6YcZaAAFDShxA+ox59t1ZuXYH06Q2UDJFlcKk/f8uotoe02ztDPzyjeJvpGFzfxiNESBw8tfMoucZZTRI+C6rgOS/wNRJYt64E=
  - secure: QxsMczt/3KeOc1bF6Xcv9OjQRa3F8ZTlyP3oYBHqi++/cl12lcdK388rs0KkAQWDfuAZUP2oqBhsmPCxklLzLHWmU0uvlQi2LMg+3XMMVaAbvpfQVTzuQCavoOoZ73p2qzto4JkCpKzV1F3Zp3LJznNAhT38L4U+aaajzrWTzDM=
  - secure: WAq4iFipx615FhtJ5izDXgbPl2wESln6nZkE4v1xcmYMnNEq11FLRPB98A50G/mDfXkHgwKRCF3ZZ+W3FpHPxKCF9LAPcGL6yIMtw83mJQTFPFYRGpHuHleDNoDOdR155hIMWXyoV+/kr1odpWumH+a2AzcxpVeZsUr2foAL+ro=
  - secure: HqNupEqZeYFo+fSXvQWRy88ntIjIJPGmEwk+Wx5LCLB+xx8PjLxNAEP0El5cvhJV6ch1zD6iJtlg5fkOTAZL24rDAH+Y9QJwkDAUTG5ArLE6wGmkWzjzlSDVjRlcq7Qw3UV/PGn2iaw1RMt8RIGrt18zCboKh4Rh60rll5f2UxA=
  - secure: dIPLNPm1GPu5AAOk26Ewh1+r0Lf9l1cei82QyZM24GzfbFcg8HFdt0+yeZ0xImv6x3M5k/QzFf6n1vvNO0w8fjikeUX9eJQQD+KLitGB6zIFcTk2oCyz3xcFrk8oRKtwVeXMB06hC15CZ2UpdbYqxBnV5USxw9JOKpLVmwRc+g0=
  - secure: RrrM7ycmA6Moyz7+sFqk/uJ1WUgB/zZqIFMyopJVc1Cvoo6/hUdqBMykBWLLDVl6jby0ZPdVB9ysTtDUWdx2oIj1STfQWieUcQpc8bY5tsOPZyiwE8FU0ZduEOR4V/6OMCrjbveYlQpExF/Vw1dN3bp+kQELgbyLCRvxUI1UbSo=
  - secure: fW2lbWNpO69Fbt1wVfm6lDVEKTRI41/XCIi6rWx9VowS/kioWfrRoSoSBpVL6I63Pjg5f1SAIuozBY7TWu9gCsZZUW1C1rNU9r5F5QjVVqWStqiU/xMsyEbtf4PK0ZcCvfwAVsQ/qCOgkHK99NLwDWYGqc7lI/1PWj7XoG55AFg=
  - secure: jQz2fwS+k1hkDI2boUG4vXBPzzrEQMTaMx4lfX79jlble+AN4oMRDl2qQX+SmwfyxKfP7rvw3zvsXf8PP9f4qDdjd+2kTRhINSWZQw9Wc7fbuQPEUQrHw9A0nVZ3f1BmiQRJphu7qjvGBms0on9gprrtFT6p1EOJbwvCjTMjJ0U=
  - secure: GMbH6+WzeOrx9bMTGqS9W2cntiOpU0gYj4YFPOyKsNMxBa9H0SSIdCQomSgb2MnRGNJMKftg9JWGzGrP1fHrVRtYNL1gn9XLSSBez31VikMUVTTlyYbZ8P30I67VTvvd3EaXuIqZh+WQ1qDKnw5jDrl5AwNeyAPW+/dt0vxpsiA=
  - KITCHEN_INSTANCE='confluence-jira-crowd-ubuntu-1204'
